"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { apiFetch, ApiRequestError } from "@/lib/api-client";
import { getCompanyToken } from "@/lib/company-auth";

interface Area { id: number; name: string }
interface Vacancy { id: string; title: string; description: string; location: string; area: string; employment_type: string; experience_years: number; deadline: string | null; status: string; moderation_reason: string | null; external_application_url: string | null; created_at: string }
const input = "w-full rounded border border-outline-variant bg-surface-container-lowest px-3 py-2 font-body text-body-md text-on-surface";

export default function CompanyVacanciesPage() {
  const [areas, setAreas] = useState<Area[]>([]); const [items, setItems] = useState<Vacancy[]>([]); const [message, setMessage] = useState<string | null>(null); const [editing, setEditing] = useState<string | null>(null);
  const headers = () => ({ Authorization: `Bearer ${getCompanyToken()}` });
  const load = () => { if (!getCompanyToken()) return; apiFetch<{ data: Vacancy[] }>("/api/v1/vacancies/mine", { headers: headers() }).then((r) => setItems(r.data)).catch(() => setMessage("No se pudieron cargar sus vacantes.")); };
  useEffect(() => { apiFetch<{ areas: Area[] }>("/api/v1/catalogs").then((r) => setAreas(r.areas)); load(); }, []);
  const payload = (form: FormData) => ({ title: form.get("title"), description: form.get("description"), location: form.get("location"), area_id: Number(form.get("area_id")), employment_type: form.get("employment_type"), experience_years: Number(form.get("experience_years")), deadline: form.get("deadline") || undefined, external_application_url: form.get("external_application_url") || null });
  const create = async (form: FormData) => { setMessage(null); try { await apiFetch("/api/v1/vacancies", { method: "POST", headers: headers(), body: JSON.stringify(payload(form)) }); setMessage("Vacante enviada para aprobación."); form.set("title", ""); load(); } catch (error) { setMessage(error instanceof ApiRequestError ? error.body.message : "No se pudo crear la vacante."); } };
  const update = async (id: string, form: FormData) => { try { await apiFetch(`/api/v1/vacancies/${id}`, { method: "PATCH", headers: headers(), body: JSON.stringify(payload(form)) }); setEditing(null); setMessage("Cambios enviados para nueva aprobación."); load(); } catch (error) { setMessage(error instanceof ApiRequestError ? error.body.message : "No se pudo actualizar la vacante."); } };
  const changeStatus = async (id: string, action: "close" | "reopen") => { try { await apiFetch(`/api/v1/vacancies/${id}/${action}`, { method: "POST", headers: headers() }); setMessage(action === "close" ? "Vacante cerrada." : "Vacante reenviada para aprobación."); load(); } catch (error) { setMessage(error instanceof ApiRequestError ? error.body.message : "No se pudo actualizar la vacante."); } };
  const fields = (vacancy?: Vacancy) => <><input name="title" required minLength={5} defaultValue={vacancy?.title} className={input} placeholder="Cargo"/><textarea name="description" required minLength={80} defaultValue={vacancy?.description} className={input} rows={5} placeholder="Descripción y requisitos"/><div className="grid gap-4 sm:grid-cols-2"><input name="location" required defaultValue={vacancy?.location} className={input} placeholder="Ciudad o modalidad"/><select name="area_id" required defaultValue={areas.find((area) => area.name === vacancy?.area)?.id ?? ""} className={input}><option value="">Área</option>{areas.map((area) => <option key={area.id} value={area.id}>{area.name}</option>)}</select><select name="employment_type" defaultValue={vacancy?.employment_type ?? "Tiempo Completo"} className={input}><option>Tiempo Completo</option><option>Por Proyecto</option><option>Asesoría/Consultoría</option></select><input name="experience_years" type="number" min="0" defaultValue={vacancy?.experience_years ?? 0} className={input}/><input name="deadline" type="date" defaultValue={vacancy?.deadline ?? ""} className={input}/><input name="external_application_url" type="url" defaultValue={vacancy?.external_application_url ?? ""} className={input} placeholder="Enlace al portal de empleos (opcional)"/></div></>;
  return <section className="mx-auto w-full max-w-3xl px-margin-mobile py-12"><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="font-headline text-headline-lg text-primary-container">Mis vacantes</h1><div className="flex gap-4"><Link href="/search" className="font-label text-label-md text-primary-container hover:underline">Buscar talento</Link><Link href="/company/profile" className="font-label text-label-md text-primary-container hover:underline">Perfil de empresa</Link></div></div>{message && <p className="mt-4 rounded border border-border-subtle p-3 font-body text-body-sm text-on-surface-variant">{message}</p>}<form action={create} className="mt-6 grid gap-4 rounded-xl border border-border-subtle bg-surface-container-lowest p-6"><h2 className="font-headline text-headline-md">Publicar nueva vacante</h2>{fields()}<button className="rounded-full bg-primary-container px-6 py-3 font-label text-label-md text-on-primary">Enviar vacante</button></form><div className="mt-8 space-y-3">{items.map((item) => <article key={item.id} className="rounded-xl border border-border-subtle p-4"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-headline text-headline-md">{item.title}</h2><p className="font-body text-body-sm text-on-surface-variant">{item.status} · {item.location}</p></div><div className="flex gap-2">{item.status !== "closed" && <button type="button" onClick={() => changeStatus(item.id, "close")} className="rounded border border-outline-variant px-3 py-1.5 font-label text-label-sm">Cerrar</button>}{item.status === "closed" && <button type="button" onClick={() => changeStatus(item.id, "reopen")} className="rounded border border-outline-variant px-3 py-1.5 font-label text-label-sm">Volver a publicar</button>}<button type="button" onClick={() => setEditing(editing === item.id ? null : item.id)} className="rounded border border-outline-variant px-3 py-1.5 font-label text-label-sm">Editar</button></div></div>{item.external_application_url && <a href={item.external_application_url} target="_blank" rel="noreferrer" className="mt-2 inline-block font-label text-label-sm text-primary-container hover:underline">Ver portal de empleo</a>}{item.moderation_reason && <p className="mt-2 font-body text-body-sm text-error">Observación: {item.moderation_reason}</p>}{editing === item.id && <form action={(form) => update(item.id, form)} className="mt-4 grid gap-4 border-t border-border-subtle pt-4">{fields(item)}<button className="rounded-full bg-primary-container px-6 py-3 font-label text-label-md text-on-primary">Guardar y reenviar a aprobación</button></form>}</article>)}</div></section>;
}
